### ISSUE TITLE
Switch to `ndk-context`

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#201]
## Description
As Hotham has several direct and indirect dependencies that in turn depend upon `ndk-glue`, we should switch to the new `ndk-context` system which would allow us to avoid running into issues when our version does not match that of upstream.

## TODO
- [ ] Use `ndk-context` where appropriate

**Comment by jmgao** [comment]
It looks like this is actively broken now if you delete Cargo.lock: we're depending on cpal `^0.13.5`  which depends on oboe `^0.4`. oboe `0.4.6` was released two days ago, which starts depending on ndk-context, so new projects or projects after you delete Cargo.lock will have ndk-glue `0.6.0` and an uninitialized `ndk-context`.

It doesn't seems trivial to convert over to ndk-context because all it gives us is a JavaVM or JNI Context. It looks like we need to jump through a bunch of JNI hoops to get the assetmanager we were getting from ndk-glue. I think the best option is for us to switch to depending on ndk-glue `>= 0.6.1`
