### ISSUE TITLE
[Rendering] Dithering

### ISSUE THREAD

**Issue by rasmusgo** [leetvr/hotham#390]
## Description
Because 8 bits is too little for storing smooth gradients without noticeable banding, we should consider adding dithering to compensate.

https://computergraphics.stackexchange.com/questions/5904/whats-a-proper-way-to-clamp-dither-noise/8777#8777 is the state of the art according to @Ralith.

## TODO
- [ ] Implement dithering in sRGB color space.

**Comment by Ralith** [comment]
Banding is generally only noticeable for *perfectly smooth* gradients. In other words you don't need it once you have textures applied, so long as those textures are not themselves mainly solid, flat colors. Since dithering isn't free (you either need to bake it into every fragment shader, or use a HDR framebuffer and dither in the tonemapping pass) it's probably best to take advantage of texturing to avoid it entirely in resource-constrained environments.

**Comment by kanerogers** [comment]
Given that this only really applies to un-textured objects and could have a very significant impact on performance I think it's best to close this one off for now!
